# Generated by Django 3.0.4 on 2020-03-31 00:57

from django.db import migrations, models
import fittings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('udpated', models.DateTimeField(auto_now=True)),
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('kid_name', models.CharField(max_length=200, verbose_name='아동이름')),
                ('parent_name', models.CharField(max_length=200, verbose_name='법정대리인 이름')),
                ('location', models.CharField(max_length=200, verbose_name='거주지')),
                ('birthdate', models.DateField(verbose_name='생년월일')),
                ('phone_number', models.CharField(max_length=200, verbose_name='연락처')),
                ('height', models.IntegerField(verbose_name='키')),
                ('weight', models.IntegerField(verbose_name='몸무게')),
                ('check1', models.BooleanField(verbose_name='개인정보 수집 및 활용 동의')),
                ('check2', models.BooleanField(verbose_name='개인정보 수집 및 활용 동의2')),
                ('chair_width', models.IntegerField(verbose_name='좌폭')),
                ('back_height', models.IntegerField(verbose_name='등 높이')),
                ('leg_length', models.IntegerField(verbose_name='다리 길이')),
                ('seat_depth', models.IntegerField(verbose_name='좌석 깊이')),
                ('front_picture', models.ImageField(upload_to=fittings.models.Fitting.front_image_path, verbose_name='정면사진')),
                ('side_picture', models.ImageField(upload_to=fittings.models.Fitting.front_image_path, verbose_name='측면사진')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
